version: '3.7'
services:
  server:
    container_name: notangles-server
    image: notangles-server
    restart: always
    build: .
    depends_on:
      - database.notangles-db
    ports:
      - '3001:3001'
    links:
      - database.notangles-db

  database.notangles-db:
    container_name: notangles-database
    restart: always
    image: postgres:alpine
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
    name: server
