# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: autotimetabler.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x61utotimetabler.proto\"\x7f\n\x14TimetableConstraints\x12\r\n\x05start\x18\x01 \x01(\x05\x12\x0b\n\x03\x65nd\x18\x02 \x01(\x05\x12\x0c\n\x04\x64\x61ys\x18\x03 \x01(\t\x12\x0b\n\x03gap\x18\x04 \x01(\x05\x12\x0f\n\x07maxdays\x18\x05 \x01(\x05\x12\x1f\n\x17periods_list_serialized\x18\x06 \x01(\t\"&\n\x15\x41utoTimetableResponse\x12\r\n\x05times\x18\x01 \x03(\x02\x32T\n\x0e\x41utoTimetabler\x12\x42\n\x11\x46indBestTimetable\x12\x15.TimetableConstraints\x1a\x16.AutoTimetableResponseb\x06proto3')



_TIMETABLECONSTRAINTS = DESCRIPTOR.message_types_by_name['TimetableConstraints']
_AUTOTIMETABLERESPONSE = DESCRIPTOR.message_types_by_name['AutoTimetableResponse']
TimetableConstraints = _reflection.GeneratedProtocolMessageType('TimetableConstraints', (_message.Message,), {
  'DESCRIPTOR' : _TIMETABLECONSTRAINTS,
  '__module__' : 'autotimetabler_pb2'
  # @@protoc_insertion_point(class_scope:TimetableConstraints)
  })
_sym_db.RegisterMessage(TimetableConstraints)

AutoTimetableResponse = _reflection.GeneratedProtocolMessageType('AutoTimetableResponse', (_message.Message,), {
  'DESCRIPTOR' : _AUTOTIMETABLERESPONSE,
  '__module__' : 'autotimetabler_pb2'
  # @@protoc_insertion_point(class_scope:AutoTimetableResponse)
  })
_sym_db.RegisterMessage(AutoTimetableResponse)

_AUTOTIMETABLER = DESCRIPTOR.services_by_name['AutoTimetabler']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TIMETABLECONSTRAINTS._serialized_start=24
  _TIMETABLECONSTRAINTS._serialized_end=151
  _AUTOTIMETABLERESPONSE._serialized_start=153
  _AUTOTIMETABLERESPONSE._serialized_end=191
  _AUTOTIMETABLER._serialized_start=193
  _AUTOTIMETABLER._serialized_end=277
# @@protoc_insertion_point(module_scope)
